"""Agregando tabla de Ventas y DetallesVentas

Revision ID: 11c71ff4c44d
Revises: 
Create Date: 2025-05-30 01:53:45.313550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11c71ff4c44d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('inventariable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('existencia',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('monto_totla')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto_totla', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('monto_total')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('existencia',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('inventariable',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
