"""Agregar tablas Ventas y DetallesVentras tras eliminarlas

Revision ID: 6bdf3254345a
Revises: 11c71ff4c44d
Create Date: 2025-05-30 15:54:16.316046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bdf3254345a'
down_revision = '11c71ff4c44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cliente', sa.String(length=100), nullable=True),
    sa.Column('empleado', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('detalles_ventas',
    sa.Column('id_registro_ventas', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_registro_ventas')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_ventas')
    op.drop_table('ventas')
    # ### end Alembic commands ###
